### PR TITLE
fix(compose): Fix compose file path resolution as it is copied into the lando config directory

### PR DESCRIPTION
**Pull request by florianPat**
Hey there,
to work with lando as a drop in replacement for docker-compose and the "compose" config feature, the paths to env_files, volume definitions and build contexts need to be resolved correctly. As the docker compose files get copied into the lando compose config directory, these paths change from the compose project directory. This pull request aims to resolve issue 3373, which explains this issue.
It creates a new docker compose routing method to use the docker compose config command to generate the config relative to the target directory (lando-dir/compose/project-name), so that every docker compose stack just works with lando (for an example, see [this commit](https://github.com/florianPat/symfony-demo/commit/747175ffce73f8576747f00ca094b1fe27585996#diff-307b4548b91e997f23c35d90ed5e9a044e156b90425c9923d6b85d7dc11e67e2).
Moreover, the app_mount can be disabled globally for every service due to a top level app_mount config, and one does not have to disable it for every service.

I would love some feedback on this feature.

Thanks in advance,
Flo

### CODE REVIEW

**Comment by reynoldsalec** [comment]
@florianPat thanks for taking a swing at this, looks interesting!

Note that I just got the tests are running with this repo's secrets, so you can use those to develop against if you're still interested in working on this. Thanks again!

**Comment by florianPat** [comment]
Hey @reynoldsalec,
could you approve the workflows once again, so that I can develop against the tests?
I would love to finish this, as our team would benefit from this feature to adapt the lando tooling and not having to refactor the docker-compose files.

Thanks in advance,
Flo

**Comment by florianPat** [comment]
Hey @reynoldsalec,
it looks like the secrets do not get picked up by the action run. Could you look at it again?

Thanks in advance,
Flo

**Comment by lochmueller** [comment]
Looks very cool. That would be helpful for my projects...

**Comment by florianPat** [comment]
Will close this till I have the actions sorted out to that you do not get notifications on every push. :)

**Comment by florianPat** [comment]
Will close this till I have the actions sorted out to that you do not get notifications on every push. :)

**Pull request closed without merging**
