### PR TITLE
chore: update docs to include Orbstack as drop-in replacement

### PR DESCRIPTION
**Pull request by arzola**
I think is a good way to work with Orbstack while Lando 4 is ready to go.

https://github.com/lando/core/issues/138

### CODE REVIEW

**Comment by arzola** [comment]
Let me know if should I add this to the MacOS install section instead

**Comment by reynoldsalec** [comment]
@arzola I booted up Orbstack and from my brief trial it looks promising. That said, this should be a [guide](https://github.com/lando/core/tree/main/docs/guides), since it won't be an "official" solution.

**Comment by arzola** [comment]
@reynoldsalec I like that I will create a guide then :)

**Comment by reynoldsalec** [comment]
Maybe a good idea to also include a note that, if you switch back to Docker Desktop you'll probably need to relink `docker.sock` manually (ie `sudo rm /var/run/docker.sock && sudo ln -s ~/.docker/run/docker.sock /var/run/docker.sock`). Not sure if there are other "gotchas" in that arena, but it wouldn't surprise me if people bounce back and forth to try out Orbstack.

**Comment by arzola** [comment]
I didn't have that issue @reynoldsalec if I uninstall or close Orbstack and open Docker App it works without having to recreate the symlink, but I can append that just in case

**Pull request closed without merging**
