### PR TITLE
#244: Variable for setting the network limit.

### LINKED ISSUE #244: Lando starts removing old networks because of Docker's network limit
I am running Lando v3.1.4 on Debian 10 and have a few dozen Lando apps. I run a nightly script that backups all the databases of my Lando apps, so all apps are started and then stopped when the script has finished. In the morning, when I manually start some apps I'm working on, chances are that one of them will complain that "Lando has detected you are at Docker's network limit!" and it starts removing some old networks. Consequently, I will have to rebuild other apps that have their network removed on a daily basis.

I thought I could get around this by increasing the Docker network limit, so I followed [theses suggustions](https://serverfault.com/a/942176) and created /etc/docker/daemon.json with the following contents:

`{
  "bip": "10.200.0.1/24",
  "default-address-pools":[
    {"base":"10.201.0.0/16","size":24},
    {"base":"10.202.0.0/16","size":24}
  ]
}`

This should increase the Docker network limit by the hundreds, if I understand correctly, yet Lando does not seem to be aware of this because it is still complaining about the Docker network limit. Is there anything else I can try to increase my network limit? Or is this a limitation of Lando?

### PR DESCRIPTION
**Pull request by reynoldsalec**
I could add in a test to make sure the config variable gets set correctly in the `config` tests. If you want me to go whole hog @pirog I could set up a new test example with more than 32 sites to test this out as well, but wanted to get your feedback on this in general.

### CODE REVIEW

**Comment by jerome-pilotin** [comment]
I'm sorry to ask, but is there any ETA on this merge? I have a need to have around 80 Lando containers running at the same time, which requires for now to prioritize things over others

**Comment by pirog** [comment]
i think @reynoldsalec wanted to get some tests in here and then i can merge it in

**Comment by reynoldsalec** [comment]
@pirog as long as the network test passes, should be good to bring into edge.

**Comment by jerome-pilotin** [comment]
Thank you @pirog and @reynoldsalec :raised_hands: I cannot tell you how much it will help us with our use case!

**Pull request merged**
